### ISSUE TITLE
Smoketests release version for Cloud Foundry version 1.12 

### ISSUE THREAD

**Issue by Murugan2all** [cloudfoundry/cf-smoke-tests-release#7] opened 2018-12-05 09:46 UTC
Hi Team

Please let us now the smoketest version which we can test for Cloud Foundry version 1.12? In the Pivotal docs its mentioned to use smoketest-38.

https://docs.pivotal.io/pivotalcf/1-12/pcf-release-notes/runtime-rn.html#1.12.9.

How we can get the github for the specific smoketest-38.

We are going to test this in PRODUCTION environment.

Regards
Murugan D

**Comment by Changdrew** [comment] 2018-12-06 19:33
Closing this because it is a duplicate of [cf-smoke-tests #46](https://github.com/cloudfoundry/cf-smoke-tests/issues/46)

**Closed by Changdrew** 2018-12-06 19:33 UTC
Labels: duplicate
